version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.atlassian.oai:swagger-request-validator-mockmvc
    versions:
    - 2.13.0
    - 2.14.0
    - 2.15.0
    - 2.15.1
    - 2.17.0
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-allopen
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.6
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
